[phases.setup]
nixPkgs = ["..#php83", "..#php83Extensions.pdo", "..#php83Extensions.pdo_sqlite", "..#php83Extensions.sqlite3", "..#php83Extensions.mbstring", "..#php83Extensions.xml", "..#php83Extensions.curl", "..#php83Extensions.gd", "..#php83Extensions.bcmath", "..#php83Extensions.intl", "..#php83Extensions.zip", "..#php83Extensions.fileinfo", "..#php83Extensions.tokenizer", "..#nodejs_20", "..#sqlite"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan key:generate --force",
    "touch database/database.sqlite",
    "php artisan migrate --force",
    "php artisan storage:link",
    "php artisan optimize"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
